In [3]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
pd.__version__

'2.3.3'

In [7]:
s = pd.Series([1,2,3,4])

In [8]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
# access

In [10]:
s[0]

np.int64(1)

In [11]:
# dataframe

In [12]:
x = {
    "name" : ["duha","tahr","muhamed"],
    "age" : [20,50,16],
    "score" : [90.0,77.0,66.7]
}

In [13]:
type(x)

dict

In [14]:
df = pd.DataFrame(x)

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
# index

In [17]:
df = pd.DataFrame(x , index=["a","b","c"])

In [18]:
df

      name  age  score
a     duha   20   90.0
b     tahr   50   77.0
c  muhamed   16   66.7

In [19]:
x

{'name': ['duha', 'tahr', 'muhamed'],
 'age': [20, 50, 16],
 'score': [90.0, 77.0, 66.7]}

In [20]:
# columns
df = pd.DataFrame(x , columns=["name","age"])

In [21]:
df

      name  age
0     duha   20
1     tahr   50
2  muhamed   16

In [22]:
# arr > df

In [23]:
arr = np.random.randint(1,10,(3,3))

In [24]:
arr

array([[2, 1, 3],
       [1, 6, 6],
       [8, 1, 4]], dtype=int32)

In [25]:
df = pd.DataFrame(arr)

In [26]:
df

   0  1  2
0  2  1  3
1  1  6  6
2  8  1  4

In [27]:
# access columns feature

In [28]:
df = pd.DataFrame(x)

In [29]:
df

      name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [30]:
# one column

In [31]:
df.name

0       duha
1       tahr
2    muhamed
Name: name, dtype: object

In [32]:
# access row

In [33]:
# loc, iloc

In [34]:
df.loc[0]

name     duha
age        20
score    90.0
Name: 0, dtype: object

In [35]:
df.iloc[0]

name     duha
age        20
score    90.0
Name: 0, dtype: object

In [36]:
df.loc[0:2]

      name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [37]:
df.iloc[0:2]

   name  age  score
0  duha   20   90.0
1  tahr   50   77.0

In [38]:
# set condition

In [39]:
df

      name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [40]:
df["age"]>20

0    False
1     True
2    False
Name: age, dtype: bool

In [41]:
df[df["age"]>20]

   name  age  score
1  tahr   50   77.0

In [42]:
(df["age"]> 20 )& (df["score"]>50)

0    False
1     True
2    False
dtype: bool

In [43]:
# rename col

In [44]:
df

      name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [45]:
df.rename({"name":"Name"}, axis = 1, inplace=True)

In [46]:
df

      Name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [47]:
# add col

In [48]:
df["gender"] = ["F","M","F"]

In [49]:
df

      Name  age  score gender
0     duha   20   90.0      F
1     tahr   50   77.0      M
2  muhamed   16   66.7      F

In [50]:
# drop col

In [51]:
df.drop([0])

      Name  age  score gender
1     tahr   50   77.0      M
2  muhamed   16   66.7      F

In [52]:
#concate

In [53]:
x

{'name': ['duha', 'tahr', 'muhamed'],
 'age': [20, 50, 16],
 'score': [90.0, 77.0, 66.7]}

In [54]:
df1 = pd.DataFrame({
    "name" : ["duha","tahr","muhamed"],
    "age" : [20,50,16],
    "score" : [90.0,77.0,66.7]
})
df2 = pd.DataFrame({
    "name" : ["adam","tahr","muhamed"],
    "A_ge" : [7,50,16],
    "S_core" : [70.0,75.0,63.7]    
})

In [55]:
df1

      name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [56]:
df2

      name  A_ge  S_core
0     adam     7    70.0
1     tahr    50    75.0
2  muhamed    16    63.7

In [57]:
pd.concat([df1,df2])

      name   age  score  A_ge  S_core
0     duha  20.0   90.0   NaN     NaN
1     tahr  50.0   77.0   NaN     NaN
2  muhamed  16.0   66.7   NaN     NaN
0     adam   NaN    NaN   7.0    70.0
1     tahr   NaN    NaN  50.0    75.0
2  muhamed   NaN    NaN  16.0    63.7

In [58]:
pd.concat([df1,df2], ignore_index=True)

      name   age  score  A_ge  S_core
0     duha  20.0   90.0   NaN     NaN
1     tahr  50.0   77.0   NaN     NaN
2  muhamed  16.0   66.7   NaN     NaN
3     adam   NaN    NaN   7.0    70.0
4     tahr   NaN    NaN  50.0    75.0
5  muhamed   NaN    NaN  16.0    63.7

In [59]:
# join

In [60]:
inner_df = pd.merge(df1,df2, on="name")

In [61]:
inner_df

      name  age  score  A_ge  S_core
0     tahr   50   77.0    50    75.0
1  muhamed   16   66.7    16    63.7

In [62]:
# sort by value

In [63]:
df1 = pd.DataFrame({
    "name" : ["duha","tahr","muhamed"],
    "age" : [20,50,16],
    "score" : [90.0,77.0,66.7]
})

In [64]:
df

      Name  age  score gender
0     duha   20   90.0      F
1     tahr   50   77.0      M
2  muhamed   16   66.7      F

In [65]:
df.sort_values(by= "age")

      Name  age  score gender
2  muhamed   16   66.7      F
0     duha   20   90.0      F
1     tahr   50   77.0      M

In [66]:
df.sort_values(by= "age", ascending=False)

      Name  age  score gender
1     tahr   50   77.0      M
0     duha   20   90.0      F
2  muhamed   16   66.7      F

In [67]:
# sample random

In [68]:
df

      Name  age  score gender
0     duha   20   90.0      F
1     tahr   50   77.0      M
2  muhamed   16   66.7      F

In [69]:
df.sample(n=2)

      Name  age  score gender
1     tahr   50   77.0      M
2  muhamed   16   66.7      F

In [70]:
df.sample(frac=0.5)

      Name  age  score gender
0     duha   20   90.0      F
2  muhamed   16   66.7      F

In [71]:
# sort by index

In [72]:
df1.sort_index()

      name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [73]:
df1

      name  age  score
0     duha   20   90.0
1     tahr   50   77.0
2  muhamed   16   66.7

In [74]:
# replace

In [75]:
df = pd.DataFrame({
    "name" : ["duha","tahr","muhamed"],
    "age" : [20,50,16],
    "score" : [90.0,77.0,66.7],
    "gender": ['F','M','M']
})

In [76]:
df

      name  age  score gender
0     duha   20   90.0      F
1     tahr   50   77.0      M
2  muhamed   16   66.7      M

In [77]:
df["gender"]=df["gender"].replace({"M":"male"})

In [78]:
df

      name  age  score gender
0     duha   20   90.0      F
1     tahr   50   77.0   male
2  muhamed   16   66.7   male

In [79]:
# groupby , aggregation

In [80]:
df.groupby("gender")["score"].mean()

gender
F       90.00
male    71.85
Name: score, dtype: float64

In [81]:
df.groupby("gender").agg({"score":"mean", "age":"max"})

        score  age
gender
F       90.00   20
male    71.85   50

In [82]:
# apply > text

In [83]:
df = pd.DataFrame({
    "Name": ["aya","ahmed","omer","alic","bob"],
    "Age" : [25,24,22,26,20],
    "Salary" : [10000,20000,34000,50000,45000],
    "Gender" : ["F","M","M","F","M"],
    "Annul_Income" : [120000,300000,100000,450000,700000],
    
})

In [95]:
len(df)

5

In [84]:
# ADD Col

In [85]:
import numpy as np

In [107]:
df["bouns"]=np.random.randint(1,1000, len(df))

In [109]:
df

    Name  Age  Income  Gender  Annul_Income  bouns
0    aya   25   10000  female        120000    487
1  ahmed   24   20000    male        300000    819
2   omer   22   34000    male        100000    123
3   alic   26   50000  female        450000    358
4    bob   20   45000    male        700000    201

In [110]:
df

    Name  Age  Income  Gender  Annul_Income  bouns
0    aya   25   10000  female        120000    487
1  ahmed   24   20000    male        300000    819
2   omer   22   34000    male        100000    123
3   alic   26   50000  female        450000    358
4    bob   20   45000    male        700000    201

In [111]:
df.rename({"Salary":"Income"}, axis = 1, inplace=True)

In [90]:
df

    Name  Age  Income Gender  Annul_Income  bouns
0    aya   25   10000      F        120000     30
1  ahmed   24   20000      M        300000     40
2   omer   22   34000      M        100000     44
3   alic   26   50000      F        450000    100
4    bob   20   45000      M        700000    333

In [91]:
df["Gender"]=df["Gender"].replace({"M":"male","F":"female"})

In [92]:
df["Gender"]

0    female
1      male
2      male
3    female
4      male
Name: Gender, dtype: object

In [93]:
# sort by value

In [94]:
df.sort_values(by= "Income")

    Name  Age  Income  Gender  Annul_Income  bouns
0    aya   25   10000  female        120000     30
1  ahmed   24   20000    male        300000     40
2   omer   22   34000    male        100000     44
4    bob   20   45000    male        700000    333
3   alic   26   50000  female        450000    100

In [112]:
# read data

In [113]:
df =pd.read_csv(r"C:\Users\DELL\Downloads\Iris.csv")

In [116]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,NaN,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  147 non-null    float64
 2   SepalWidthCm   146 non-null    float64
 3   PetalLengthCm  148 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [117]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           NaN            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [118]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [119]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     147.000000    146.000000     148.000000    150.000000
mean    75.500000       5.861224      3.047945       3.787838      1.198667
std     43.445368       0.821996      0.435212       1.758165      0.763161
min      1.000000       4.400000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.400000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [120]:
df["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [121]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [122]:
df["Species"].nunique()

3

In [123]:
df.isna().sum()

Id               0
SepalLengthCm    3
SepalWidthCm     4
PetalLengthCm    2
PetalWidthCm     0
Species          0
dtype: int64

In [124]:
# duplication

In [127]:
df.duplicated().sum()

np.int64(0)

In [129]:
df.drop_duplicates(inplace=True)

In [128]:
# save