In [ ]:
# Data Loading & Inspection Load the company_ data. csv file. Print the first 10 rows and use a Pandas method to show the data types and check for missing values in each column.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\company_data.csv")

In [3]:
print(df.head(10))

   Employee_ID Employee_Name Department    Salary  Years_Experience  \
0          101      John Doe         IT   85000.0                 5
1          102    Jane Smith         HR   60000.0                 3
2          103   Ali Mansour      Sales       NaN                12
3          104      Sara Lee         IT   95000.0                 1
4          105     Ben Clark    Finance   70000.0                 8
5          106     Eva Green      Sales   55000.0                 4
6          107      Mona Ray         HR       NaN                 2
7          108      Leo King         IT  105000.0                10
8          109      Tom Cook    Finance   72000.0                 6
9          110     Anna Bell         IT   88000.0                 9

   Evaluation_Score   Bonus
0                88  5000.0
1                72  3000.0
2                95  7000.0
3                45     NaN
4                60  4000.0
5                82  2000.0
6                55     NaN
7                91  8000.0
8                78  4500.0
9                40  2500.0

In [4]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       20 non-null     int64
 1   Employee_Name     20 non-null     str
 2   Department        20 non-null     str
 3   Salary            18 non-null     float64
 4   Years_Experience  20 non-null     int64
 5   Evaluation_Score  20 non-null     int64
 6   Bonus             18 non-null     float64
dtypes: float64(2), int64(3), str(2)
memory usage: 1.2 KB
None

In [5]:
print(df.isnull() .sum())

Employee_ID         0
Employee_Name       0
Department          0
Salary              2
Years_Experience    0
Evaluation_Score    0
Bonus               2
dtype: int64

In [ ]:
# Handling Missing Values The dataset contains missing values in the Salary and Bonus columns.
# • Fill the missing Salary values with the median salary of the entire company.
# • Fill the missing bouns values with 0

In [6]:
median_salary = df["Salary"].median()

In [7]:
df["Salary"].fillna(median_salary,  inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10076\2416687628.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Salary"].fillna(median_salary,  inplace=True)

0      85000.0
1      60000.0
2      73500.0
3      95000.0
4      70000.0
5      55000.0
6      73500.0
7     105000.0
8      72000.0
9      88000.0
10     58000.0
11     62000.0
12     92000.0
13     54000.0
14     75000.0
15    110000.0
16     63000.0
17     59000.0
18     98000.0
19     77000.0
Name: Salary, dtype: float64

In [8]:
df["Bonus"].fillna(0, inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10076\405026823.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Bonus"].fillna(0, inplace=True)

0     5000.0
1     3000.0
2     7000.0
3        0.0
4     4000.0
5     2000.0
6        0.0
7     8000.0
8     4500.0
9     2500.0
10    1500.0
11    3500.0
12    6000.0
13    1000.0
14    5000.0
15    9000.0
16    3200.0
17    2100.0
18    6500.0
19    4800.0
Name: Bonus, dtype: float64

In [9]:
df.isnull().sum()

Employee_ID         0
Employee_Name       0
Department          0
Salary              2
Years_Experience    0
Evaluation_Score    0
Bonus               2
dtype: int64

In [ ]:
# Data Cleaning: The Employee_Name column is in the format "FirstName LastName",
# ". Split this column into two new columns: First_Name and Last_Name,
# then delete the original Employee_Name column.

In [10]:
import pandas as pd

df[['First_Name', 'Last_Name']] = df['Employee_Name'].str.split(' ', expand=True)


df.drop('Employee_Name', axis=1, inplace=True)
df.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
0,101,IT,85000.0,5,88,5000.0,John,Doe
1,102,HR,60000.0,3,72,3000.0,Jane,Smith
2,103,Sales,NaN,12,95,7000.0,Ali,Mansour
3,104,IT,95000.0,1,45,NaN,Sara,Lee
4,105,Finance,70000.0,8,60,4000.0,Ben,Clark

In [ ]:
# Filtering :Create a new DataFrame called Senior_IT that contains only employees from the 'IT' department who have more than 8 years of experience.

In [11]:
Senior_IT = df[(df["Department"] == "IT") & (df["Years_Experience"] > 8)]

Senior_IT

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
7,108,IT,105000.0,10,91,8000.0,Leo,King
9,110,IT,88000.0,9,40,2500.0,Anna,Bell
12,113,IT,92000.0,11,77,6000.0,Will,Smith
15,116,IT,110000.0,15,98,9000.0,Bruce,Wayne
18,119,IT,98000.0,9,81,6500.0,Barry,Allen

In [ ]:
# 5. Performance Mapping Create a new column called Performance_Level based on the Evaluation_Score (1-100):
# • Score > 80: "High"
# • Score 50-80: "Medium"
# • Score < 50: "Low"

In [12]:
def performance_level(score):
    if score>80:
        return"high"
    elif score<80:
        return"medium"
    else:
        return"low"
df["Performance_Level"] = df["Evaluation_Score"].apply(performance_level)
    
df.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
0,101,IT,85000.0,5,88,5000.0,John,Doe,high
1,102,HR,60000.0,3,72,3000.0,Jane,Smith,medium
2,103,Sales,NaN,12,95,7000.0,Ali,Mansour,high
3,104,IT,95000.0,1,45,NaN,Sara,Lee,medium
4,105,Finance,70000.0,8,60,4000.0,Ben,Clark,medium

In [ ]:
# Calculate the total salary expense and the average evaluation score for each Department

In [13]:
depart_summary = df.groupby("Department").agg({
    "Salary":"sum",
    "Evaluation_Score": "mean"})
depart_summary

              Salary  Evaluation_Score
Department
Finance     294000.0         74.250000
HR          185000.0         71.500000
IT          673000.0         74.285714
Sales       226000.0         67.600000

In [ ]:
# 7. Find the top 5 highest-paid employees in the company. Print only their names and salaries.

In [14]:
top_5 = df.sort_values(by="Salary", ascending=False)

top_5[["First_Name", "Last_Name", "Salary"]].head(5)

   First_Name Last_Name    Salary
15      Bruce     Wayne  110000.0
7         Leo      King  105000.0
18      Barry     Allen   98000.0
3        Sara       Lee   95000.0
12       Will     Smith   92000.0

In [ ]:

#  The company is giving a 10% raise to everyone in the 'Sales' department. Update the Salary column for those employees only.

In [24]:
df.loc[df["Department"] == "Sales", "Salary"] *= 1.10

In [ ]:
# 9. Exporting Results Save the final, cleaned, and updated DataFrame to a new Excel or CSV file named final_employee_report.csv.

In [25]:
df.to_csv("final_employee_report.csv",  index=False)